name: Java CI

on: [ push ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - run: gradle build publish --no-daemon
        env:
          SIGNING_SECRET_KEY: ${{ secrets.DEPLOY_GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.DEPLOY_GPG_PRIVATE_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
